### ISSUE TITLE
Structure initiale du projet

### ISSUE THREAD

**Issue by SamAI10** [SamAI10/shopify-dhl-tracking#1]
Voici la structure initiale du projet à implémenter :

### 1. `shopify.app.toml`
```toml
[app]
name = "DHL Tracking Integration"

[[extensions]]
type = "ui_extension"
name = "dhl-tracking-extension"
handle = "dhl-tracking-extension"
target = "admin"
```

### 2. `package.json`
```json
{
  "name": "shopify-dhl-tracking",
  "version": "1.0.0",
  "description": "Module d'intégration du suivi DHL pour Shopify",
  "main": "index.js",
  "scripts": {
    "test": "jest",
    "dev": "shopify app dev",
    "build": "shopify app build",
    "deploy": "shopify app deploy"
  },
  "dependencies": {
    "@shopify/app": "^3.0.0",
    "@shopify/shopify-api": "^7.0.0",
    "axios": "^1.6.0"
  },
  "devDependencies": {
    "@shopify/cli": "^3.0.0",
    "jest": "^29.0.0"
  }
}
```

### 3. Structure des dossiers
```
/extensions
  /dhl-tracking-extension
    /src
      /components
        - TrackingBlock.js
      - index.js
/web
  /backend
    - index.js
```

### 4. Configuration initiale
- Mettre en place l'environnement de développement
- Configurer les variables d'environnement pour DHL
- Initialiser l'extension Shopify

## Prochaines étapes
1. Créer la structure des dossiers
2. Implémenter les composants React
3. Configurer l'API DHL
4. Mettre en place les tests
5. Documenter l'installation et l'utilisation
